COMP: Specify list VTK_MAKE_INSTANTIATOR3 input as list of cxx files only.
This commit fixes a build error introduced by kitware/VTK@5c3241b9d8
It ensures there are no duplicated entries in the instantiator files.

The error (reported below) was first discovered when building Slicer
on MacOSX 10.6 with the option VTK_ENABLE_KITS while working on issue
#3741.

// ------------------------
$ make vtkSlicerTransformsModuleMRMLDisplayableManager/fast
[ 59%] Building CXX object Modules/Loadable/Transforms/MRMLDM/CMakeFiles/vtkSlicerTransformsModuleMRMLDisplayableManager.dir/TransformsInstantiator.cxx.o
/path/to/Slicer-build/Modules/Loadable/Transforms/MRMLDM/TransformsInstantiator.cxx: In function 'vtkObject* vtkInstantiatorvtkMRMLTransformsDisplayableManager2DNew()':
/path/to/Slicer-build/Modules/Loadable/Transforms/MRMLDM/TransformsInstantiator.cxx:10: error: redefinition of 'vtkObject* vtkInstantiatorvtkMRMLTransformsDisplayableManager2DNew()'
/path/to/Slicer-build/Modules/Loadable/Transforms/MRMLDM/TransformsInstantiator.cxx:9: error: 'vtkObject* vtkInstantiatorvtkMRMLTransformsDisplayableManager2DNew()' previously defined here
/path/to/Slicer-build/Modules/Loadable/Transforms/MRMLDM/TransformsInstantiator.cxx: In function 'vtkObject* vtkInstantiatorvtkMRMLTransformsDisplayableManager3DNew()':
/path/to/Slicer-build/Modules/Loadable/Transforms/MRMLDM/TransformsInstantiator.cxx:12: error: redefinition of 'vtkObject* vtkInstantiatorvtkMRMLTransformsDisplayableManager3DNew()'
/path/to/Slicer-build/Modules/Loadable/Transforms/MRMLDM/TransformsInstantiator.cxx:11: error: 'vtkObject* vtkInstantiatorvtkMRMLTransformsDisplayableManager3DNew()' previously defined here
make[1]: *** [Modules/Loadable/Transforms/MRMLDM/CMakeFiles/vtkSlicerTransformsModuleMRMLDisplayableManager.dir/TransformsInstantiator.cxx.o] Error 1
make: *** [vtkSlicerTransformsModuleMRMLDisplayableManager/fast] Error 2
// ------------------------

The content of the associated instantiator file was:

// ---------------
$ cat Modules/Loadable/Transforms/MRMLDM/TransformsInstantiator.cxx

[...]

vtkInstantiatorNewMacro(vtkMRMLTransformsDisplayableManager2D)
vtkInstantiatorNewMacro(vtkMRMLTransformsDisplayableManager2D)
vtkInstantiatorNewMacro(vtkMRMLTransformsDisplayableManager3D)
vtkInstantiatorNewMacro(vtkMRMLTransformsDisplayableManager3D)

[...]
// ---------------

This commit avoid the duplicated entries in the instantiator file.

git-svn-id: http://svn.slicer.org/Slicer4/trunk@23508 3bd1e089-480b-0410-8dfb-8563597acbee