BUG: Fix data download URLs and Slicer display message call
Fix data download URLs and Slicer display message call in test:
- The Slicer testing data was moved from kitware midas hosting to GitHub
  repositories. Related thread:
  https://github.com/Slicer/Slicer/pull/4785
- Use the `slicer.util` module to be able to call the `delayDisplay`
  method: the testing class `DTINotReproducibleIssue3977Logic` inherits
  from `ScriptedLoadableModuleLogic`, which does not have a parent
  class, and thus does not inherit the `delayDisplay` (as opposed to
  classes that inherit from `ScriptedLoadableModuleTest`.

Fixes:
```
   File "SlicerDMRI/Modules/Loadable/TractographyDisplay/Testing/Python/DTINotReproducibleIssue3977.py",
line 147, in test_DTINotReproducibleIssue39771
     volumeNode = slicer.util.getNode(pattern="dwi")
   File "SlicerDMRI/Slicer-build/Slicer-build/bin/Python/slicer/util.py",
line 1517, in getNode
     raise MRMLNodeNotFoundException("could not find nodes in the scene by name or id '%s'" % (pattern if (isinstance(pattern, str)) else ""))
 slicer.util.MRMLNodeNotFoundException: could not find nodes in the scene by name or id 'dwi'
```

raised for exampled at:
https://github.com/SlicerDMRI/SlicerDMRI/actions/runs/6722459285/job/18270424711?pr=191#step:8:1317

and
```
   File "SlicerDMRI/Modules/Loadable/TractographyDisplay/Testing/Python/DTINotReproducibleIssue3977.py",
line 155, in test_DTINotReproducibleIssue39771
     (outputBaseline, outputFA) = logic.computeFA(volumeNode)
   File "SlicerDMRI/Modules/Loadable/TractographyDisplay/Testing/Python/DTINotReproducibleIssue3977.py",
line 79, in computeFA
     self.delayDisplay(module.title)
 AttributeError: 'DTINotReproducibleIssue3977Logic' object has no attribute 'delayDisplay'
```