BUG: Fix syntax errors raised after introducing f-strings
Fix syntax errors raised after introducing f-strings.

Fixes:
```
SlicerDMRI-build/inner-build/lib/Slicer-5.7/qt-scripted-modules/DICOMDiffusionVolumePlugin.py, line 115
    loadable.tooltip = f"Matches DICOM tags for the following vendor(s): {', '.join(matchingVendors)}")
                                                                                                      ^
SyntaxError: unmatched ')'
```

and
```
SlicerDMRI-build/inner-build/lib/Slicer-5.7/qt-scripted-modules/TractographyExportPLY.py, line 306
   self.delayDisplay(f"Test caused exception!\n"{str(e)}")
                                                ^
SyntaxError: invalid syntax
```

raised for example at:
https://github.com/SlicerDMRI/SlicerDMRI/actions/runs/7130356243/job/19416548387#step:8:541
https://github.com/SlicerDMRI/SlicerDMRI/actions/runs/7130356243/job/19416548387#step:8:559

Introduced inadvertently in commit 56b282f.