BUG: Fix qSlicerDICOM2FullBrainTractographyModuleGenericTest
Fix the following warning introduced in 72fbe0f0b (BUG: Replace saferef
with weakref) by make the callback methods be methods of the `Workflow`
class.

Fixes:
```
test_widgetRepresentation
(qSlicerDICOM2FullBrainTractographyModuleGenericTest.
qSlicerDICOM2FullBrainTractographyModuleGenericTest)
... Traceback (most recent call last):
  File "SlicerDMRI-build/inner-build/lib/Slicer-5.4/qt-scripted-modules/DICOM2FullBrainTractography.py",
 line 44, in setup
    self.full_tractography_workflow = DICOM2FullBrainTractographyLib.Workflow(
  File "SlicerDMRI-build/inner-build/lib/Slicer-5.4/qt-scripted-modules/DICOM2FullBrainTractographyLib/workflow_support.py",
 line 82, in __init__
    step = GeneralizedStep(step_widget_file, widget,
  File "SlicerDMRI-build/inner-build/lib/Slicer-5.4/qt-scripted-modules/DICOM2FullBrainTractographyLib/workflow_support.py",
 line 135, in __init__
    self.weak_onEntryCallback = weakref.WeakMethod(onEntryCallback)
  File "python-install/lib/python3.9/weakref.py", line 52, in __new__
    raise TypeError("argument should be a bound method, not {}"
TypeError: argument should be a bound method, not <class 'function'>
```

Co-authored-by: Jean-Christophe Fillion-Robin <jchris.fillionr@kitware.com>