BUG: Fix syntax errors raised after introducing f-strings (follow-up)
Fix syntax errors raised after introducing f-strings.

Fixes:
```
Compiling qt-scripted-modules/DICOM2FullBrainTractographyLib/workflow_support.py ...
  File "qt-scripted-modules/DICOM2FullBrainTractographyLib/workflow_support.py", line 240
    this_module.__all__.append(function_name)
    ^
SyntaxError: invalid syntax
```

raised for example at:
https://github.com/SlicerDMRI/SlicerDMRI/actions/runs/7132804489/job/19424129633?pr=224#step:7:272

Introduced inadvertently in commit 56b282f and left behind in ee1f772.